#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLichHoc.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Lesson_Management")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLecture(Lecture instance);
    partial void UpdateLecture(Lecture instance);
    partial void DeleteLecture(Lecture instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::QuanLyLichHoc.Properties.Settings.Default.Lesson_ManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Lecture> Lectures
		{
			get
			{
				return this.GetTable<Lecture>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lecture")]
	public partial class Lecture : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LectureID;
		
		private string _LectureName;
		
		private string _LectureGender;
		
		private string _LectureAddress;
		
		private string _LectureStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLectureIDChanging(int value);
    partial void OnLectureIDChanged();
    partial void OnLectureNameChanging(string value);
    partial void OnLectureNameChanged();
    partial void OnLectureGenderChanging(string value);
    partial void OnLectureGenderChanged();
    partial void OnLectureAddressChanging(string value);
    partial void OnLectureAddressChanged();
    partial void OnLectureStatusChanging(string value);
    partial void OnLectureStatusChanged();
    #endregion
		
		public Lecture()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LectureID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LectureID
		{
			get
			{
				return this._LectureID;
			}
			set
			{
				if ((this._LectureID != value))
				{
					this.OnLectureIDChanging(value);
					this.SendPropertyChanging();
					this._LectureID = value;
					this.SendPropertyChanged("LectureID");
					this.OnLectureIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LectureName", DbType="NVarChar(255)")]
		public string LectureName
		{
			get
			{
				return this._LectureName;
			}
			set
			{
				if ((this._LectureName != value))
				{
					this.OnLectureNameChanging(value);
					this.SendPropertyChanging();
					this._LectureName = value;
					this.SendPropertyChanged("LectureName");
					this.OnLectureNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LectureGender", DbType="NVarChar(255)")]
		public string LectureGender
		{
			get
			{
				return this._LectureGender;
			}
			set
			{
				if ((this._LectureGender != value))
				{
					this.OnLectureGenderChanging(value);
					this.SendPropertyChanging();
					this._LectureGender = value;
					this.SendPropertyChanged("LectureGender");
					this.OnLectureGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LectureAddress", DbType="NVarChar(255)")]
		public string LectureAddress
		{
			get
			{
				return this._LectureAddress;
			}
			set
			{
				if ((this._LectureAddress != value))
				{
					this.OnLectureAddressChanging(value);
					this.SendPropertyChanging();
					this._LectureAddress = value;
					this.SendPropertyChanged("LectureAddress");
					this.OnLectureAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LectureStatus", DbType="NVarChar(255)")]
		public string LectureStatus
		{
			get
			{
				return this._LectureStatus;
			}
			set
			{
				if ((this._LectureStatus != value))
				{
					this.OnLectureStatusChanging(value);
					this.SendPropertyChanging();
					this._LectureStatus = value;
					this.SendPropertyChanged("LectureStatus");
					this.OnLectureStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
